### ISSUE TITLE
Every function should have a counterpart that does not require Unicode

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix-stdlib#59]
I am unable to type Unicode composition symbol directly in the VSCode REPL. This issue also affects other Unicode symbols. As a workaround, users must either copy-paste the symbol or find an extension that provides Unicode input support in the terminal (which is different from the editor).
In principle, we should always have a counterpart not involving Unicode.
We already discussed this at some point and agreed on it. 

https://github.com/anoma/juvix-stdlib/blob/c3f0ec0f3e64bbaee503e4514164087b1b7fe705/Stdlib/Function.juvix#L16

**Comment by janmasrovira** [comment]
In the case of composition, we should probably use dot, as in Haskell. This will require some extra work in the parser/lexer however

**Comment by jonaprieto** [comment]
The dot is fine for the infix symbol. For a function name, I can live with something that matches this regex`((map|fun)-)?comp(isition)?`

**Comment by jonaprieto** [comment]
> what's the justification for wanting a name other than `.`?

Not everyone is familiar with this particular use of the dot symbol. Period.

**Comment by paulcadman** [comment]
We could use `(>>)` and `(<<)` for function composition (from elm):

https://package.elm-lang.org/packages/elm/core/latest/Basics#(%3C%3C)
